// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public final class BootNode {
  private BootNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_GetRoutingArrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_GetRoutingArrayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017boot_node.proto\022\034com.messaging.bootNod" +
      "e.stubs\"(\n\030BootstrapBootNodeRequest\022\014\n\004p" +
      "ort\030\001 \001(\r\"1\n\031BootstrapBootNodeResponse\022\024" +
      "\n\014routingArray\030\001 \003(\r\"(\n\030BootstrapPeerNod" +
      "eRequest\022\014\n\004port\030\001 \001(\r\"1\n\031BootstrapPeerN" +
      "odeResponse\022\024\n\014routingArray\030\001 \003(\r\"4\n\034Pro" +
      "pogateRoutingArrayRequest\022\024\n\014routingArra" +
      "y\030\001 \003(\r\"\037\n\035PropogateRoutingArrayResponse" +
      "\"\030\n\026GetRoutingArrayRequest\"/\n\027GetRouting" +
      "ArrayResponse\022\024\n\014routingArray\030\001 \003(\r2\262\004\n\017",
      "BootNodeService\022\204\001\n\021bootstrapBootNode\0226." +
      "com.messaging.bootNode.stubs.BootstrapBo" +
      "otNodeRequest\0327.com.messaging.bootNode.s" +
      "tubs.BootstrapBootNodeResponse\022\204\001\n\021boots" +
      "trapPeerNode\0226.com.messaging.bootNode.st" +
      "ubs.BootstrapPeerNodeRequest\0327.com.messa" +
      "ging.bootNode.stubs.BootstrapPeerNodeRes" +
      "ponse\022~\n\017getRoutingArray\0224.com.messaging" +
      ".bootNode.stubs.GetRoutingArrayRequest\0325" +
      ".com.messaging.bootNode.stubs.GetRouting",
      "ArrayResponse\022\220\001\n\025propogateRoutingArray\022" +
      ":.com.messaging.bootNode.stubs.Propogate" +
      "RoutingArrayRequest\032;.com.messaging.boot" +
      "Node.stubs.PropogateRoutingArrayResponse" +
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor,
        new java.lang.String[] { "Port", });
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor,
        new java.lang.String[] { "RoutingArray", });
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor,
        new java.lang.String[] { "Port", });
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor,
        new java.lang.String[] { "RoutingArray", });
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayRequest_descriptor,
        new java.lang.String[] { "RoutingArray", });
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_PropogateRoutingArrayResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_GetRoutingArrayRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_messaging_bootNode_stubs_GetRoutingArrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_GetRoutingArrayResponse_descriptor,
        new java.lang.String[] { "RoutingArray", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
