// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public interface BootstrapPeerNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.bootNode.stubs.BootstrapPeerNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addr = 1;</code>
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddrBytes();
}
