// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public interface BootstrapPeerNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.bootNode.stubs.BootstrapPeerNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 port = 1;</code>
   */
  int getPort();
}
