// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public interface BootstrapPeerNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.bootNode.stubs.BootstrapPeerNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, bool&gt; routingTable = 1;</code>
   */
  int getRoutingTableCount();
  /**
   * <code>map&lt;string, bool&gt; routingTable = 1;</code>
   */
  boolean containsRoutingTable(
      java.lang.String key);
  /**
   * Use {@link #getRoutingTableMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getRoutingTable();
  /**
   * <code>map&lt;string, bool&gt; routingTable = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getRoutingTableMap();
  /**
   * <code>map&lt;string, bool&gt; routingTable = 1;</code>
   */

  boolean getRoutingTableOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <code>map&lt;string, bool&gt; routingTable = 1;</code>
   */

  boolean getRoutingTableOrThrow(
      java.lang.String key);
}
