// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public final class BootNode {
  private BootNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_RoutingTableEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_RoutingTableEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_RoutingTableEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_RoutingTableEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017boot_node.proto\022\034com.messaging.bootNod" +
      "e.stubs\"(\n\030BootstrapBootNodeRequest\022\014\n\004a" +
      "ddr\030\001 \001(\t\"\261\001\n\031BootstrapBootNodeResponse\022" +
      "_\n\014routingTable\030\001 \003(\0132I.com.messaging.bo" +
      "otNode.stubs.BootstrapBootNodeResponse.R" +
      "outingTableEntry\0323\n\021RoutingTableEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\010:\0028\001\"(\n\030Bootstr" +
      "apPeerNodeRequest\022\014\n\004addr\030\001 \001(\t\"\261\001\n\031Boot" +
      "strapPeerNodeResponse\022_\n\014routingTable\030\001 " +
      "\003(\0132I.com.messaging.bootNode.stubs.Boots",
      "trapPeerNodeResponse.RoutingTableEntry\0323" +
      "\n\021RoutingTableEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\010:\0028\0012\237\002\n\017BootNodeService\022\204\001\n\021boot" +
      "strapBootNode\0226.com.messaging.bootNode.s" +
      "tubs.BootstrapBootNodeRequest\0327.com.mess" +
      "aging.bootNode.stubs.BootstrapBootNodeRe" +
      "sponse\022\204\001\n\021bootstrapPeerNode\0226.com.messa" +
      "ging.bootNode.stubs.BootstrapPeerNodeReq" +
      "uest\0327.com.messaging.bootNode.stubs.Boot" +
      "strapPeerNodeResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeRequest_descriptor,
        new java.lang.String[] { "Addr", });
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor,
        new java.lang.String[] { "RoutingTable", });
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_RoutingTableEntry_descriptor =
      internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_RoutingTableEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapBootNodeResponse_RoutingTableEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeRequest_descriptor,
        new java.lang.String[] { "Addr", });
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor,
        new java.lang.String[] { "RoutingTable", });
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_RoutingTableEntry_descriptor =
      internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_RoutingTableEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_bootNode_stubs_BootstrapPeerNodeResponse_RoutingTableEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
