// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public interface GetRoutingArrayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.bootNode.stubs.GetRoutingArrayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 routingArray = 1;</code>
   */
  java.util.List<java.lang.Integer> getRoutingArrayList();
  /**
   * <code>repeated uint32 routingArray = 1;</code>
   */
  int getRoutingArrayCount();
  /**
   * <code>repeated uint32 routingArray = 1;</code>
   */
  int getRoutingArray(int index);
}
