// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boot_node.proto

package com.messaging.bootNode.stubs;

public interface GetRoutingArrayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.bootNode.stubs.GetRoutingArrayRequest)
    com.google.protobuf.MessageOrBuilder {
}
