// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.peerNode.stubs.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool sent = 1;</code>
   */
  boolean getSent();
}
