// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public final class PeerNode {
  private PeerNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_peerNode_stubs_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_peerNode_stubs_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_messaging_peerNode_stubs_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_messaging_peerNode_stubs_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017peer_node.proto\022\034com.messaging.peerNod" +
      "e.stubs\"!\n\016MessageRequest\022\017\n\007message\030\001 \001" +
      "(\t\"\037\n\017MessageResponse\022\014\n\004sent\030\001 \001(\0102}\n\017P" +
      "eerNodeService\022j\n\013sendMessage\022,.com.mess" +
      "aging.peerNode.stubs.MessageRequest\032-.co" +
      "m.messaging.peerNode.stubs.MessageRespon" +
      "seB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_messaging_peerNode_stubs_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_messaging_peerNode_stubs_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_peerNode_stubs_MessageRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_messaging_peerNode_stubs_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_messaging_peerNode_stubs_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_messaging_peerNode_stubs_MessageResponse_descriptor,
        new java.lang.String[] { "Sent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
