// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public interface RegisterPeerNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.peerNode.stubs.RegisterPeerNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 port = 1;</code>
   */
  int getPort();
}
