// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public interface RegisterPeerNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.peerNode.stubs.RegisterPeerNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool registered = 1;</code>
   */
  boolean getRegistered();
}
