// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

/**
 * Protobuf type {@code com.messaging.peerNode.stubs.RegisterPeerNodeResponse}
 */
public  final class RegisterPeerNodeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.messaging.peerNode.stubs.RegisterPeerNodeResponse)
    RegisterPeerNodeResponseOrBuilder {
  // Use RegisterPeerNodeResponse.newBuilder() to construct.
  private RegisterPeerNodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterPeerNodeResponse() {
    registered_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RegisterPeerNodeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            registered_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.messaging.peerNode.stubs.RegisterPeerNodeResponse.class, com.messaging.peerNode.stubs.RegisterPeerNodeResponse.Builder.class);
  }

  public static final int REGISTERED_FIELD_NUMBER = 1;
  private boolean registered_;
  /**
   * <code>bool registered = 1;</code>
   */
  public boolean getRegistered() {
    return registered_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (registered_ != false) {
      output.writeBool(1, registered_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (registered_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, registered_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.messaging.peerNode.stubs.RegisterPeerNodeResponse)) {
      return super.equals(obj);
    }
    com.messaging.peerNode.stubs.RegisterPeerNodeResponse other = (com.messaging.peerNode.stubs.RegisterPeerNodeResponse) obj;

    boolean result = true;
    result = result && (getRegistered()
        == other.getRegistered());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGISTERED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRegistered());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.messaging.peerNode.stubs.RegisterPeerNodeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.messaging.peerNode.stubs.RegisterPeerNodeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.messaging.peerNode.stubs.RegisterPeerNodeResponse)
      com.messaging.peerNode.stubs.RegisterPeerNodeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messaging.peerNode.stubs.RegisterPeerNodeResponse.class, com.messaging.peerNode.stubs.RegisterPeerNodeResponse.Builder.class);
    }

    // Construct using com.messaging.peerNode.stubs.RegisterPeerNodeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      registered_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeResponse_descriptor;
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeResponse getDefaultInstanceForType() {
      return com.messaging.peerNode.stubs.RegisterPeerNodeResponse.getDefaultInstance();
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeResponse build() {
      com.messaging.peerNode.stubs.RegisterPeerNodeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeResponse buildPartial() {
      com.messaging.peerNode.stubs.RegisterPeerNodeResponse result = new com.messaging.peerNode.stubs.RegisterPeerNodeResponse(this);
      result.registered_ = registered_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.messaging.peerNode.stubs.RegisterPeerNodeResponse) {
        return mergeFrom((com.messaging.peerNode.stubs.RegisterPeerNodeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.messaging.peerNode.stubs.RegisterPeerNodeResponse other) {
      if (other == com.messaging.peerNode.stubs.RegisterPeerNodeResponse.getDefaultInstance()) return this;
      if (other.getRegistered() != false) {
        setRegistered(other.getRegistered());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.messaging.peerNode.stubs.RegisterPeerNodeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.messaging.peerNode.stubs.RegisterPeerNodeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean registered_ ;
    /**
     * <code>bool registered = 1;</code>
     */
    public boolean getRegistered() {
      return registered_;
    }
    /**
     * <code>bool registered = 1;</code>
     */
    public Builder setRegistered(boolean value) {
      
      registered_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool registered = 1;</code>
     */
    public Builder clearRegistered() {
      
      registered_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.messaging.peerNode.stubs.RegisterPeerNodeResponse)
  }

  // @@protoc_insertion_point(class_scope:com.messaging.peerNode.stubs.RegisterPeerNodeResponse)
  private static final com.messaging.peerNode.stubs.RegisterPeerNodeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.messaging.peerNode.stubs.RegisterPeerNodeResponse();
  }

  public static com.messaging.peerNode.stubs.RegisterPeerNodeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterPeerNodeResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterPeerNodeResponse>() {
    public RegisterPeerNodeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterPeerNodeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterPeerNodeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterPeerNodeResponse> getParserForType() {
    return PARSER;
  }

  public com.messaging.peerNode.stubs.RegisterPeerNodeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

