// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

/**
 * Protobuf type {@code com.messaging.peerNode.stubs.RegisterPeerNodeRequest}
 */
public  final class RegisterPeerNodeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.messaging.peerNode.stubs.RegisterPeerNodeRequest)
    RegisterPeerNodeRequestOrBuilder {
  // Use RegisterPeerNodeRequest.newBuilder() to construct.
  private RegisterPeerNodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterPeerNodeRequest() {
    port_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RegisterPeerNodeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            port_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.messaging.peerNode.stubs.RegisterPeerNodeRequest.class, com.messaging.peerNode.stubs.RegisterPeerNodeRequest.Builder.class);
  }

  public static final int PORT_FIELD_NUMBER = 1;
  private int port_;
  /**
   * <code>uint32 port = 1;</code>
   */
  public int getPort() {
    return port_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (port_ != 0) {
      output.writeUInt32(1, port_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, port_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.messaging.peerNode.stubs.RegisterPeerNodeRequest)) {
      return super.equals(obj);
    }
    com.messaging.peerNode.stubs.RegisterPeerNodeRequest other = (com.messaging.peerNode.stubs.RegisterPeerNodeRequest) obj;

    boolean result = true;
    result = result && (getPort()
        == other.getPort());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.messaging.peerNode.stubs.RegisterPeerNodeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.messaging.peerNode.stubs.RegisterPeerNodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.messaging.peerNode.stubs.RegisterPeerNodeRequest)
      com.messaging.peerNode.stubs.RegisterPeerNodeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.messaging.peerNode.stubs.RegisterPeerNodeRequest.class, com.messaging.peerNode.stubs.RegisterPeerNodeRequest.Builder.class);
    }

    // Construct using com.messaging.peerNode.stubs.RegisterPeerNodeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      port_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.messaging.peerNode.stubs.PeerNode.internal_static_com_messaging_peerNode_stubs_RegisterPeerNodeRequest_descriptor;
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeRequest getDefaultInstanceForType() {
      return com.messaging.peerNode.stubs.RegisterPeerNodeRequest.getDefaultInstance();
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeRequest build() {
      com.messaging.peerNode.stubs.RegisterPeerNodeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.messaging.peerNode.stubs.RegisterPeerNodeRequest buildPartial() {
      com.messaging.peerNode.stubs.RegisterPeerNodeRequest result = new com.messaging.peerNode.stubs.RegisterPeerNodeRequest(this);
      result.port_ = port_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.messaging.peerNode.stubs.RegisterPeerNodeRequest) {
        return mergeFrom((com.messaging.peerNode.stubs.RegisterPeerNodeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.messaging.peerNode.stubs.RegisterPeerNodeRequest other) {
      if (other == com.messaging.peerNode.stubs.RegisterPeerNodeRequest.getDefaultInstance()) return this;
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.messaging.peerNode.stubs.RegisterPeerNodeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.messaging.peerNode.stubs.RegisterPeerNodeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int port_ ;
    /**
     * <code>uint32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>uint32 port = 1;</code>
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 port = 1;</code>
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.messaging.peerNode.stubs.RegisterPeerNodeRequest)
  }

  // @@protoc_insertion_point(class_scope:com.messaging.peerNode.stubs.RegisterPeerNodeRequest)
  private static final com.messaging.peerNode.stubs.RegisterPeerNodeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.messaging.peerNode.stubs.RegisterPeerNodeRequest();
  }

  public static com.messaging.peerNode.stubs.RegisterPeerNodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterPeerNodeRequest>
      PARSER = new com.google.protobuf.AbstractParser<RegisterPeerNodeRequest>() {
    public RegisterPeerNodeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterPeerNodeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterPeerNodeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterPeerNodeRequest> getParserForType() {
    return PARSER;
  }

  public com.messaging.peerNode.stubs.RegisterPeerNodeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

