// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public interface SendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.peerNode.stubs.SendMessageResponse)
    com.google.protobuf.MessageOrBuilder {
}
