// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_node.proto

package com.messaging.peerNode.stubs;

public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.messaging.peerNode.stubs.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>uint32 targetPort = 2;</code>
   */
  int getTargetPort();
}
